server {
    listen 80;
    server_name localhost;

    location = / {
        root /usr/share/nginx/html;
        try_files /index.html =404;
    }

    location = /index.html {
        root /usr/share/nginx/html;
        try_files /index.html =404;
    }

    location = /2026.png {
        root /usr/share/nginx/html;
        try_files /2026.png =404;
    }

    location = /banner.jpg {
        root /usr/share/nginx/html;
        try_files /banner.jpg =404;
    }

    location / {
        return 404;
    }
}
